# Generated by Django 6.1.1 on 2026-09-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_wallettransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="lean_customer_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
