# Generated by Django 6.1.1 on 2026-09-16 05:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market", models.CharField(default="DEMO/USD", max_length=50)),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("RISE", "Rise"), ("FALL", "Fall")], max_length=10
                    ),
                ),
                ("stake", models.DecimalField(decimal_places=2, max_digits=15)),
                ("entry_price", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("duration_seconds", models.PositiveIntegerField(default=60)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("WON", "Won"),
                            ("LOST", "Lost"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "profit_loss",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
